kind: pipeline
name: default
workspace:
  base: /app
  path: .

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: index.hduin.club/interview
    registry: index.hduin.club
    username: drone
    password: dronelogin
    mirror: https://fhvwls99.mirror.aliyuncs.com
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_SHA:0:8}
  when:
    branch:
    - master
      
- name: update-service
  image: redhome/docker-cli
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - docker login index.hduin.club --username drone --password dronelogin
  - docker pull index.hduin.club/interview:${DRONE_COMMIT_BRANCH}
  - docker service update --image index.hduin.club/interview:${DRONE_COMMIT_BRANCH} --with-registry-auth redhome-interview
  when:
    branch:
    - master

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  branch: 
  - master 