kind: pipeline
name: default
workspace:
  base: /app
  path: .

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: redreg.redhome.cc/interview
    registry: redreg.redhome.cc
    username: drone
    password: dronelogin
    mirror: https://fhvwls99.mirror.aliyuncs.com
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    debug: true
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_SHA:0:8}
  when:
    branch:
    - master
      
- name: update-service
  image: redhome/docker-cli
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - docker login redreg.redhome.cc --username drone --password dronelogin
  - docker pull redreg.redhome.cc/interview:${DRONE_COMMIT_BRANCH}
  - docker service update --image redreg.redhome.cc/interview:${DRONE_COMMIT_BRANCH} --with-registry-auth redhome-interview
  when:
    branch:
    - master

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  branch: 
  - master 